PosetiMe/PosetiMe/Controllers/LocalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PosetiMe.Models;
using Microsoft.AspNet.Identity;
using NLog;

namespace PosetiMe.Controllers
{
    public class LocalsController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        
        private DBPosetiMeEntities db = new DBPosetiMeEntities();

        // GET: Locals
        public ActionResult Index()
        {
            var tblLocals = db.tblLocals.Include(t => t.tblCity);
            return View(tblLocals.ToList());
        }

        // GET: Locals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLocal tblLocal = db.tblLocals.Find(id);
            if (tblLocal == null)
            {
                return HttpNotFound();
            }

            string idUser = User.Identity.GetUserId(); //зачувување на IDUser во локална променлива кој ни е потребен за 
                                                        //наоѓање на коментарите

            //земање на сите гласови за оваа локација
            var getRate = from a in db.tblRatings
                          where a.ID_Local == id
                          select a;

            //земање на сите коментари за локалот од одреден корисник
            var getComments = from c in db.tblComments
                              where c.ID_Local == id && c.ID_User ==  idUser
                              select c;

            //пресметување на рејтингот за оваа локација
            float rateing = new int();
            foreach (tblRating r in getRate)
            {
                rateing += r.Rate;
            }
            rateing = rateing / getRate.Count();
            TempData["rateing"] = rateing;//се проследува пресметаниот рејтинг до View-то
            ViewBag.comments = getComments.ToList();//се проследуваат пронајдените коментари до view-то
            return View(tblLocal);
        }

        // GET: Locals/Create
        public ActionResult Create()
        {
            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name");
            return View();
        }

        // POST: Locals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,ID_City,Location,Phone,Phone2,Imege")] tblLocal tblLocal)
        {
            
            //Оневозможување на внесување на дупликат
            bool localExist = db.tblLocals.Any(local => local.Name.Equals(tblLocal.Name));
            if (localExist)
            {
                
                return View("LocalExistError");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.tblLocals.Add(tblLocal);
                    try
                    {
                        db.SaveChanges();
                        logger .Info("Внесен е нов локал со име "+ tblLocal.Name +".");
                    }
                    //внес на невалидни информации или недоволно информации за моделот
                    catch (Exception e)
                    {
                        return View("InformationError");
                    }
                    return RedirectToAction("Index");
                }
            }
            

            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name", tblLocal.ID_City);
            return View(tblLocal);
        }

        // GET: Locals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLocal tblLocal = db.tblLocals.Find(id);
            if (tblLocal == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name", tblLocal.ID_City);
            return View(tblLocal);
        }

        // POST: Locals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,ID_City,Location,Phone,Phone2,Imege")] tblLocal tblLocal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblLocal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name", tblLocal.ID_City);
            return View(tblLocal);
        }

        // GET: Locals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLocal tblLocal = db.tblLocals.Find(id);
            if (tblLocal == null)
            {
                return HttpNotFound();
            }
            return View(tblLocal);
        }

        // POST: Locals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblLocal tblLocal = db.tblLocals.Find(id);
            db.tblLocals.Remove(tblLocal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PosetiMe/PosetiMe/Controllers/VisitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PosetiMe.Models;
using Microsoft.AspNet.Identity;

namespace PosetiMe.Controllers
{
    public class VisitsController : Controller
    {
        private DBPosetiMeEntities db = new DBPosetiMeEntities();

        // GET: Visits
        public ActionResult Index()
        {
            var tblVisits = db.tblVisits.Include(t => t.tblLocal).Include(t => t.tblUser);

            //служи да се провери во view дали одредената посета е од најавениот корисник 
            ViewBag.user = User.Identity.GetUserId();
                return View(tblVisits.ToList());
        }

        // GET: Visits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblVisit tblVisit = db.tblVisits.Find(id);
            if (tblVisit == null)
            {
                return HttpNotFound();
            }
            tblLocal tblLocal = db.tblLocals.Find(tblVisit.ID_Local);

            int idLocal = tblLocal.ID; // потребно ни е за прашалникот за коментарите и рејтингот
            string idUser = User.Identity.GetUserId(); //зачувување на IDUser во локална променлива кој ни е потребен за 
                                                       //наоѓање на коментарите

            //земање на сите гласови за оваа локација
            var getRate = from a in db.tblRatings
                          where a.ID_Local == idLocal
                          select a;

            //земање на сите коментари за локалот од одреден корисник
            var getComments = from c in db.tblComments
                              where c.ID_Local == idLocal && c.ID_User == idUser
                              select c;

            //пресметување на рејтингот за оваа локација
            float rateing = new int();
            foreach (tblRating r in getRate)
            {
                rateing += r.Rate;
            }
            rateing = rateing / getRate.Count();
            TempData["rateing"] = rateing;//се проследува пресметаниот рејтинг до View-то
            ViewBag.comments = getComments.ToList();//се проследуваат пронајдените коментари до view-то
            return View(tblLocal);
        }

        // GET: Visits/Create
        public ActionResult Create()
        {
            ViewBag.ID_Local = new SelectList(db.tblLocals, "ID", "Name");
            //ViewBag.ID_User = new SelectList(db.tblUsers, "ID", "ID");
            return View();
        }

        // POST: Visits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,ID_User,ID_Local,Date")] tblVisit tblVisit)
        {
            tblVisit.ID_User = User.Identity.GetUserId();
            tblVisit.Date = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.tblVisits.Add(tblVisit);
                db.SaveChanges();

                //проследување на ID од штотуку внесениот локал до контролетрот Ratings
                TempData["idL"] = tblVisit.ID_Local;
                return RedirectToAction("Create", "Ratings");
            }

            ViewBag.ID_Local = new SelectList(db.tblLocals, "ID", "Name", tblVisit.ID_Local);
            ViewBag.ID_User = new SelectList(db.tblUsers, "ID", "ID", tblVisit.ID_User);
            return RedirectToAction("Create", "Rating");
        }

        // GET: Visits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblVisit tblVisit = db.tblVisits.Find(id);
            if (tblVisit == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Local = new SelectList(db.tblLocals, "ID", "Name", tblVisit.ID_Local);
            ViewBag.ID_User = new SelectList(db.tblUsers, "ID", "ID", tblVisit.ID_User);
            return View(tblVisit);
        }

        // POST: Visits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,ID_User,ID_Local,Date")] tblVisit tblVisit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblVisit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Local = new SelectList(db.tblLocals, "ID", "Name", tblVisit.ID_Local);
            ViewBag.ID_User = new SelectList(db.tblUsers, "ID", "ID", tblVisit.ID_User);
            return View(tblVisit);
        }

        // GET: Visits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblVisit tblVisit = db.tblVisits.Find(id);
            if (tblVisit == null)
            {
                return HttpNotFound();
            }
            return View(tblVisit);
        }

        // POST: Visits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblVisit tblVisit = db.tblVisits.Find(id);
            db.tblVisits.Remove(tblVisit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PosetiMe/PosetiMe/Views/Visits/Create.cshtml
@model PosetiMe.Models.tblVisit

@{
    ViewBag.Title = "Create";
}

<h2>Нова посета на локал</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Внесете податоци за новата посета</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.ID_User, "ID_User", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_User", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_User, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Local, "Име на локал", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Local", null, htmlAttributes: new { @class = "form-control col-md-9" })
                @Html.ValidationMessageFor(model => model.ID_Local, "", new { @class = "text-danger" })
                @*Икона + за додавање на нов локал во листата*@
                <a href="@Url.Action("Create", "Locals")">
                    <span class="glyphicon glyphicon-plus col-md-1",  style="padding-top: 7px;" >
                    </span>
                </a>
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Внеси" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вратете се во листата на посетени локали", "Index")
</div>

PosetiMe/PosetiMe/Views/Visits/Delete.cshtml
@model PosetiMe.Models.tblVisit

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblVisit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblLocal.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblLocal.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblUser.ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblUser.ID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PosetiMe/PosetiMe/Views/Visits/Details.cshtml
@model PosetiMe.Models.tblLocal

@{
    ViewBag.Title = "Details";
}

<h2>Детали</h2>

<div>
    <h4>за локалот</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Име
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Град
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCity.Name)
        </dd>

        <dt>
            Адреса
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            Телефон
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            Телефон 2
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone2)
        </dd>
        <dt>
            Рејтинг
        </dt>

        <dd>
            @if (Model != null)
            {
                @TempData["rateing"]
            }
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Назад кон сите мои посети", "Index")
</p>

<table class="table">
    <tr>
        <th>
            Дата
        </th>
        <th>
            Коментар
        </th>

        <th></th>
    </tr>

    @foreach (var item in ViewBag.comments)
    {
        <tr>
            <td>
                @item.Date
            </td>
            <td>
                @item.Comment
            </td>
        </tr>
    }

</table>

PosetiMe/PosetiMe/Views/Visits/Edit.cshtml
@model PosetiMe.Models.tblVisit

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblVisit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_User, "ID_User", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_User", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_User, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Local, "ID_Local", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Local", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Local, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PosetiMe/PosetiMe/Views/Visits/Index.cshtml
@model IEnumerable<PosetiMe.Models.tblVisit>

@{
    ViewBag.Title = "Index";
}

<h2>Внесување на нова посета</h2>

<p>
    @Html.ActionLink("Внеси нова посета", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Дата
        </th>
        <th>
            Локал
        </th>
        <th></th>
    </tr>
 
@foreach (var item in Model)
{
    if (item.ID_User == ViewBag.user) // проверва дали посетата на локалот е од најавениот корисник
    {
    <tr>
        <td>
            @Html.DisplayFor(Model => item.Date)
        </td>
        <td>
            @Html.DisplayFor(Model => item.tblLocal.Name)
        </td>
        <td>
            @Html.ActionLink("Детали", "Details", new { id = item.ID }) 
        </td>
    </tr>}
}

</table>