PosetiMe/PosetiMe/Controllers/CitiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PosetiMe.Models;

namespace PosetiMe.Controllers
{
    public class CitiesController : Controller
    {
        private DBPosetiMeEntities db = new DBPosetiMeEntities();

        // GET: Cities
        public ActionResult Index()
        {
            return View(db.tblCities.ToList());
        }

        // GET: Cities/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCity tblCity = db.tblCities.Find(id);
            if (tblCity == null)
            {
                return HttpNotFound();
            }
            return View(tblCity);
        }

        // GET: Cities/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cities/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name")] tblCity tblCity)
        {
            if (ModelState.IsValid)
            {
                db.tblCities.Add(tblCity);
                db.SaveChanges();
                return RedirectToAction("Create", "Locals");
            }

            return View(tblCity);
        }

        // GET: Cities/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCity tblCity = db.tblCities.Find(id);
            if (tblCity == null)
            {
                return HttpNotFound();
            }
            return View(tblCity);
        }

        // POST: Cities/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name")] tblCity tblCity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblCity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblCity);
        }

        // GET: Cities/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblCity tblCity = db.tblCities.Find(id);
            if (tblCity == null)
            {
                return HttpNotFound();
            }
            return View(tblCity);
        }

        // POST: Cities/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblCity tblCity = db.tblCities.Find(id);
            db.tblCities.Remove(tblCity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PosetiMe/PosetiMe/Controllers/LocalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PosetiMe.Models;
using Microsoft.AspNet.Identity;
using NLog;

namespace PosetiMe.Controllers
{
    public class LocalsController : Controller
    {
        private static Logger logger = LogManager.GetCurrentClassLogger();
        
        private DBPosetiMeEntities db = new DBPosetiMeEntities();

        // GET: Locals
        public ActionResult Index()
        {
            var tblLocals = db.tblLocals.Include(t => t.tblCity);
            return View(tblLocals.ToList());
        }

        // GET: Locals/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLocal tblLocal = db.tblLocals.Find(id);
            if (tblLocal == null)
            {
                return HttpNotFound();
            }

            string idUser = User.Identity.GetUserId(); //зачувување на IDUser во локална променлива кој ни е потребен за 
                                                        //наоѓање на коментарите

            //земање на сите гласови за оваа локација
            var getRate = from a in db.tblRatings
                          where a.ID_Local == id
                          select a;

            //земање на сите коментари за локалот од одреден корисник
            var getComments = from c in db.tblComments
                              where c.ID_Local == id && c.ID_User ==  idUser
                              select c;

            //пресметување на рејтингот за оваа локација
            float rateing = new int();
            foreach (tblRating r in getRate)
            {
                rateing += r.Rate;
            }
            rateing = rateing / getRate.Count();
            TempData["rateing"] = rateing;//се проследува пресметаниот рејтинг до View-то
            ViewBag.comments = getComments.ToList();//се проследуваат пронајдените коментари до view-то
            return View(tblLocal);
        }

        // GET: Locals/Create
        public ActionResult Create()
        {
            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name");
            return View();
        }

        // POST: Locals/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,ID_City,Location,Phone,Phone2,Imege")] tblLocal tblLocal)
        {
            
            //Оневозможување на внесување на дупликат
            bool localExist = db.tblLocals.Any(local => local.Name.Equals(tblLocal.Name));
            if (localExist)
            {
                
                return View("LocalExistError");
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.tblLocals.Add(tblLocal);
                    try
                    {
                        db.SaveChanges();
                        logger .Info("Внесен е нов локал со име "+ tblLocal.Name +".");
                    }
                    //внес на невалидни информации или недоволно информации за моделот
                    catch (Exception e)
                    {
                        return View("InformationError");
                    }
                    return RedirectToAction("Index");
                }
            }
            

            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name", tblLocal.ID_City);
            return View(tblLocal);
        }

        // GET: Locals/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLocal tblLocal = db.tblLocals.Find(id);
            if (tblLocal == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name", tblLocal.ID_City);
            return View(tblLocal);
        }

        // POST: Locals/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,ID_City,Location,Phone,Phone2,Imege")] tblLocal tblLocal)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblLocal).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_City = new SelectList(db.tblCities, "ID", "Name", tblLocal.ID_City);
            return View(tblLocal);
        }

        // GET: Locals/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblLocal tblLocal = db.tblLocals.Find(id);
            if (tblLocal == null)
            {
                return HttpNotFound();
            }
            return View(tblLocal);
        }

        // POST: Locals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblLocal tblLocal = db.tblLocals.Find(id);
            db.tblLocals.Remove(tblLocal);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PosetiMe/PosetiMe/Views/Locals/Create.cshtml
@model PosetiMe.Models.tblLocal

@{
    ViewBag.Title = "Create";
}


<h2>Внеси</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    

    <div class="form-horizontal">
        <h4>нов локал</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class = "control-label col-md-2" })>Име</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" })>Град</label>
            <div class="col-md-10">
                @Html.DropDownList("ID_City", null, htmlAttributes: new { @class = "form-control col-md-9" })
                @Html.ValidationMessageFor(model => model.ID_City, "", new { @class = "text-danger" })
                @*Икона + за додавање на нов локал во листата*@
                <a href="@Url.Action("Create", "Cities")">
                    <span class="glyphicon glyphicon-plus col-md-1" , style="padding-top: 7px;">
                    </span>
                </a>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" })>Адреса</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" })>Телефон</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" })>Телефон 2</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Внеси" class="btn btn-default" />
            </div>
        </div>
    </div>
}

PosetiMe/PosetiMe/Views/Locals/Delete.cshtml
@model PosetiMe.Models.tblLocal

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblLocal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imege)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imege)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tblCity.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCity.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PosetiMe/PosetiMe/Views/Locals/Details.cshtml
@model PosetiMe.Models.tblLocal 

@{
    ViewBag.Title = "Details";
}

<h2>Детали</h2>

<div>
    <h4>за локалот</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Име
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Град
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblCity.Name)
        </dd>

        <dt>
            Адреса
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            Телефон
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            Телефон 2
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone2)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.Imege)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imege)
        </dd>*@

        

        <dt>
            Рејтинг
        </dt>

        <dd>
            @if (Model != null)
            {
                @TempData["rateing"]
            }
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Назад кон сите локали", "Index")
</p>

<table class="table">
    <tr>
        <th>
            Дата
        </th>
        <th>
            Коментар
        </th>
        
        <th></th>
    </tr>

    @foreach (var item in ViewBag.comments)
    {
        <tr>
            <td>
                @item.Date
            </td>
            <td>
                @item.Comment
            </td>
        </tr>
    }

</table>

PosetiMe/PosetiMe/Views/Locals/Edit.cshtml
@model PosetiMe.Models.tblLocal

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblLocal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_City, "ID_City", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_City", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imege, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imege, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Imege, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PosetiMe/PosetiMe/Views/Locals/Index.cshtml
@model IEnumerable<PosetiMe.Models.tblLocal>

@{
    ViewBag.Title = "Index";
}

<h2>Локали</h2>

<p>
    @Html.ActionLink("Внеси нов локал", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Име
        </th>
        <th>
            Град
        </th>
        <th>
            Адреса
        </th>
        <th>
            Телефон
        </th>
        <th>
            Телефон 2
        </th>
                
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tblCity.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone2)
        </td>
       
        <td>
            @Html.ActionLink("Детали", "Details", new { id=item.ID })
        </td>
    </tr>
}

</table>

PosetiMe/PosetiMe/Views/Locals/InformationError.cshtml
@model PosetiMe.Models.tblLocal

@{
    ViewBag.Title = "InformationError";
}

<h2>Не се внесени сите потребни информации или внесените информации не се валидни</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PosetiMe/PosetiMe/Views/Locals/LocalExistError.cshtml
@model PosetiMe.Models.tblLocal

@{
    ViewBag.Title = "LocalExistError";
}

<h2>Локалот веќе постои во системот!</h2>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>